#!/bin/bash

# DSE RPC to localhost
## sed -ie 's/^rpc_address:.*/rpc_address: 0.0.0.0\nbroadcast_rpc_address: 127.0.0.1/g' /etc/dse/cassandra/cassandra.yaml

# Enable dsefs with adjusted min_free_space
sudo sed -ie 's/^\# dsefs_options:.*/dsefs_options:\n     enabled: true\n     keyspace_name: dsefs\n     work_dir: \/var\/lib\/dsefs\n     public_port: 5598\n     private_port: 5599\n     data_directories:\n           \- dir: \/var\/lib\/dsefs\/data\n             storage_weight: 1.0\n             min_free_space: 5368709\n/g' /etc/dse/dse.yaml

sudo sed -ie 's/ jps_/\#jps/' /etc/dse/dse.yaml

echo Original IPs:
grep _address /etc/dse/cassandra/cassandra.yaml|grep -v "#"
ip=$( grep listen_address /etc/dse/cassandra/cassandra.yaml|grep -v "#")
ip=${ip##* }
sudo sed -E -e's/^(native_transport_address: )([0-9].*)/\10.0.0.0/g' \
            -e"s/^(broadcast_address: )([0-9].*)/\1$ip/g" \
            -e"s/^(native_transport_broadcast_address: )([0-9].*)/\1$ip/g" \
            -i /etc/dse/cassandra/cassandra.yaml 
echo Modified IPs:
grep _address /etc/dse/cassandra/cassandra.yaml|grep -v "#"


# Enable graph
sudo sed -ie 's/GRAPH_ENABLED=0/GRAPH_ENABLED=1/g' /etc/default/dse

#Fix gremlin-console to run on localhost
## sed -ie 's/hosts: \[.*\]/hosts: \[localhost\]/g' /etc/dse/graph/gremlin-console/conf/remote.yaml
## sed -ie 's/realtime_evaluation_timeout_in_seconds: 30/realtime_evaluation_timeout_in_seconds: 180/g' /etc/dse/dse.yaml
