#!/bin/sh

myhost=`hostname`

if [ `hostname` = "node0" ]; then
  sudo service dse stop
  sleep 60
  sudo service dse start
  sleep 60
  sudo service dse start
else
  sleep 240
  sudo service dse stop
  sleep 60
  sudo service dse start
  sleep 60
  sudo service dse start
fi
