#!/bin/bash

dse client-tool alwayson-sql reconfig

cd /tmp
rm -rf /tmp/datastax-studio*
wget --no-check-certificate --content-disposition -P /tmp https://downloads.datastax.com/datastax-studio/datastax-studio-6.7.0.tar.gz
tar -xvf /tmp/datastax-studio-6.7.0.tar.gz
ln -sf /tmp/datastax-studio-6.7.0 /tmp/studio

echo "Downloading workbooks .."
test -e dse-workshop-studio.tar.gz && rm dse-workshop-studio.tar.gz
wget --no-check-certificate --content-disposition -P /tmp https://github.com/russkatz/dse-halfday-workshop/raw/master/files/dse-workshop-studio.tar.gz

echo "Configuring DSE Studio .."
sed -i 's%baseDirectory: null%baseDirectory: /tmp/studio/dse-workshop-studio%g' /tmp/studio/conf/configuration.yaml
sed -i 's%httpBindAddress: localhost%httpBindAddress: 0.0.0.0%g' /tmp/studio/conf/configuration.yaml
sed -i 's%executionTimeoutMs: 0%executionTimeoutMs: 600000%g' /tmp/studio/conf/configuration.yaml
cd /tmp/studio
tar -zxf /tmp/dse-workshop-studio.tar.gz

echo "Starting DSE Studio .."
for pid in `ps -aef | grep [s]tudio-server | awk '{print $2}'`; do kill -9 $pid; done
sleep 5

rm -rf ~/.datastax_studio
nohup /tmp/studio/bin/server.sh &

echo "http://"`curl -s http://api.ipify.org`":9091"
